name: draw_master
description: "A sandbox project to practice in building Flutter web applicatons."

version: 1.0.0

environment:
  sdk: ^3.9.0-293.0.dev

dependencies:
  uuid: ^4.4.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.2
